apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  apiDbCon: {{ .Values.apiDbCon }}
  elasticPassword: {{ .Values.elasticPassword }}
  s3AccessKeyId: {{ .Values.s3AccessKeyId }}
  s3SecretAccessKey: {{ .Values.s3SecretAccessKey }}
