image: 'swissgeol-assets-pipeline:latest'

syncView:
  sourceAllowedWorkgroupIds: '1'
  destinationAllowedWorkgroupIds:
  mode: 'view'
syncExternToIntern:
  mode: 'extern'
  sourceAllowedWorkgroupIds: '1'
  destinationAllowedWorkgroupIds:
  defaultAssignee: 'marcel.pfiffner@swisstopo.ch'
