apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  sourceConnectionString: {{ .Values.sourceConnectionString | quote }}
  destinationConnectionString: {{ .Values.destinationConnectionString | quote }}
