apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-extraction
  namespace: {{ .Release.Namespace }}
  annotations:
    keel.sh/policy: force
    keel.sh/match-tag: 'true'
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-extraction
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-extraction
    spec:
      serviceAccountName: extraction
      containers:
      - name: {{ .Release.Name }}-extraction
        image: {{ .Values.image_extraction }}
        imagePullPolicy: Always
        ports:
          - containerPort: 8000
        env:
          - name: TMP_PATH
            value: /tmp/ocr/
          - name: S3_BUCKET
            value: {{ .Values.s3_bucket_name }}
          - name: S3_FOLDER
            value: {{ .Values.s3_asset_folder }}/
          - name: AWS_PROFILE
            value: {{ .Values.s3_bucket_name }}
          - name: FASTTEXT_MODEL_PATH
            value: "models/FastText/lid.176.bin"
        resources:
          limits:
            cpu: '0.5'
            memory: '2Gi'
      imagePullSecrets:
      - name: {{ .Release.Namespace }}-registry
