apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  elasticEncryptionKey: {{ .Values.elasticEncryptionKey }}
  elasticPassword: {{ .Values.elasticPassword }}
  kibanaPassword: {{ .Values.kibanaPassword }}