@assetId = 12

### List favourites
GET {{host}}/api/assets/favorites
Authorization: Impersonate {{user}}

### Add favourite
POST {{host}}/api/assets/favorites/{{assetId}}
Authorization: Impersonate {{user}}

### Remove favourite
DELETE {{host}}/api/assets/favorites/{{assetId}}
Authorization: Impersonate {{user}}
