apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  syncViewSourceConnectionString: {{ .Values.syncView.sourceConnectionString | quote }}
  syncViewDestinationConnectionString: {{ .Values.syncView.destinationConnectionString | quote }}
  syncExternToInternSourceConnectionString: {{ .Values.syncExternToIntern.sourceConnectionString | quote }}
  syncExternToInternDestinationConnectionString: {{ .Values.syncExternToIntern.destinationConnectionString | quote }}
