### Start asset sync
POST {{host}}/api/assets/sync
Authorization: Impersonate {{user}}

### Show asset sync progress
GET {{host}}/api/assets/sync
Authorization: Impersonate {{user}}

### Search assets
POST {{host}}/api/assets/search?limit=1
Content-Type: application/json
Authorization: Impersonate {{user}}

{
  "languageItemCodes": ["DE"]
}

### Show assets search stats
POST {{host}}/api/assets/search/stats
Content-Type: application/json
Authorization: Impersonate {{user}}

{
}

