host:
image_app:
image_api:
elasticsearch_url:
s3_bucket_name:
s3_region:
s3_endpoint:
s3_asset_folder:
ocr_url:
ocr_callback_url:
oauth_issuer:
oauth_client_id:
oauth_scope:
oauth_show_debug_info:
oauth_token_endpoint:
ocr_service_account_role:
